In [7]:
import numpy as np

np.array([1,2,3])

a = np.array([1,2,3])
print(type(a))




<class 'numpy.ndarray'>


## 2D and 3D Array

In [12]:
b = np.array([[1,2,3],[4,5,6]])
#print(b)
c = np.array([[[1,2,3],[4,5,6],[7,8,9]]])
print(c)

[[[1 2 3]
  [4 5 6]
  [7 8 9]]]


Float data Array

In [14]:
np.array([1,2,3],dtype=float)


array([1., 2., 3.])

In [16]:
# np.arange

np.arange(1,11,3) # (Start, End, step)

array([ 1,  4,  7, 10])

In [20]:
# With reshape

np.arange(1,13).reshape(2,6)

array([[ 1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12]])

In [21]:
# np.ones and np.zeros

np.ones((3,4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [22]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [23]:
np.random.random((3,4))

array([[0.35218812, 0.01689886, 0.19534745, 0.55885216],
       [0.85975086, 0.73786951, 0.80128074, 0.92128155],
       [0.38918946, 0.91273568, 0.31287713, 0.48746069]])

In [24]:
# np.random

np.random.random((3,4))

array([[0.72993135, 0.21114139, 0.3117575 , 0.19189484],
       [0.76859576, 0.05705196, 0.03014556, 0.9241818 ],
       [0.77443101, 0.1697284 , 0.26677734, 0.2766481 ]])

In [26]:
# np.linspace

aa = np.linspace(-10,10,10)
print(aa)

[-10.          -7.77777778  -5.55555556  -3.33333333  -1.11111111
   1.11111111   3.33333333   5.55555556   7.77777778  10.        ]


In [27]:
# np.identity

np.identity(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# Array Attributes

In [28]:
a1 = np.arange(10)
a2 = np.arange(12, dtype=float).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)


In [31]:
# ndim(number of dimension)

a3.ndim

3

In [34]:
# shape
a3.shape


(2, 2, 2)

In [38]:
# size
a2.size


12

In [41]:
# itemsize
print(a3.itemsize)

8


In [43]:
# dtype
print(a1.dtype)
print(a2.dtype)
print(a3.dtype)

int64
float64
int64


# Changing Datatype

In [44]:
# astype
a3.astype(np.int32)

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]], dtype=int32)

# Array Operation


In [46]:
a1 = np.arange(12).reshape(3,4)
a2 = np.arange(12,24).reshape(3,4)

a2

array([[12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [50]:
# Scalar Operation


# Arithmetic
a1 ** 3

array([[   0,    1,    8,   27],
       [  64,  125,  216,  343],
       [ 512,  729, 1000, 1331]])

In [54]:
# Relational
a2 == 15 

array([[False, False, False,  True],
       [False, False, False, False],
       [False, False, False, False]])

In [58]:
# Vector Operations
   
a1 * a2

# Arithmetic

array([[  0,  13,  28,  45],
       [ 64,  85, 108, 133],
       [160, 189, 220, 253]])

# Array Function

In [60]:
a1 = np.random.random((3,3))
a1 = np.round(a1*100)

a1

array([[ 0., 72., 90.],
       [15., 96., 31.],
       [94., 86., 84.]])

In [65]:
# max/min/sum/prod
#np.max(a1)
#np.min(a1)
#np.sum(a1)
#np.prod(a1)
# 0 -> col/1 -> row
np.max(a1,axis=0)#if every indivisual col maximamul nedeed


array([94., 96., 90.])

In [67]:
# mean/median/std/var

np.median(a1)


84.0

In [68]:
# trigonometrics function
np.sin(a1)

array([[ 0.        ,  0.25382336,  0.89399666],
       [ 0.65028784,  0.98358775, -0.40403765],
       [-0.24525199, -0.92345845,  0.73319032]])

In [69]:
# dot product
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(12,24).reshape(4,3)

np.dot(a2,a3)


array([[114, 120, 126],
       [378, 400, 422],
       [642, 680, 718]])

In [70]:
# log and Exponents
np.exp(a1)

array([[1.00000000e+00, 1.85867175e+31, 1.22040329e+39],
       [3.26901737e+06, 4.92345829e+41, 2.90488497e+13],
       [6.66317622e+40, 2.23524660e+37, 3.02507732e+36]])

In [73]:
# round/floor/ceil

np.round(np.random.random((2,3))*100)

array([[38., 38.,  7.],
       [ 2., 37., 43.]])

# Indexing and Slicing

In [76]:
a1 = np.arange(10)
a2 = np.arange(12).reshape(3,4)
a3 = np.arange(8).reshape(2,2,2)

In [77]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [78]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [80]:
a3

array([[[0, 1],
        [2, 3]],

       [[4, 5],
        [6, 7]]])

In [81]:
a3[1,0,1]

5

In [85]:
a3[0,1,0]

2

In [88]:
a3[1,1,0]

6

In [89]:
a1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [90]:
a1[2:5]

array([2, 3, 4])

In [91]:
a2

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [92]:
a2[::2,::3]

array([[ 0,  3],
       [ 8, 11]])

In [93]:
a2[1:,1:3]

array([[ 5,  6],
       [ 9, 10]])